### ISSUE TITLE
there is a error

### ISSUE THREAD

**Issue by henryzp** [okoala/fis3-vue#2]
Cannot find module 'vue-resource/package.json'

![image](https://cloud.githubusercontent.com/assets/3849702/11034621/edc36cd8-8727-11e5-9cb0-10c2a399a59a.png)

**Comment by okoala** [comment]
@henryzp  安装 npm i vue-resource

**Comment by henryzp** [comment]
@okoala 
![image](https://cloud.githubusercontent.com/assets/3849702/11052657/fe5338b8-8794-11e5-93b0-c0e729a07dc8.png)

这是通过npm install下载下来的，之前的package.json文件里面
![image](https://cloud.githubusercontent.com/assets/3849702/11052685/48255458-8795-11e5-9898-d79f86947bc3.png)

我猜想是因为文件名变了，所以对应的地方也要修改。。

**Comment by henryzp** [comment]
这边我不明白的是，为什么两个文件夹命名要加一个2？？

**Comment by henryzp** [comment]
我把文件名夹名修改了一下，即将两个“2”去掉了。。之后可以跑起来了。。
但打开localhost:3000，里面什么东西都木有啊。。。

**Comment by ql2005** [comment]
我这也一样,虽然没把2去掉,release正常,页面空白
c目录只有一个c-header是正常的,其他都只有一个scss
github里看components目录里就感觉不对,是不是提交上来文件不全?

**Comment by okoala** [comment]
@ql2005   我更新下吧，这个项目很久没更新了，我看下问题~~

**Comment by ql2005** [comment]
THX @okoala ,麻烦了!~

**Comment by okoala** [comment]
Fixed
